baseurl: "https://openameba.github.io/a11y-guidelines"
title: "Ameba Accessibility Guidelines"
footnotereturnlinkcontents: "↩"
contentdir: "content"
layoutdir: "layouts"
staticdir: "static"
publishdir: "public"
uglyUrls: false
metaDataFormat: "yaml"
permalinks:
  post: "/:title"
params:
  description: Ameba Accessibility Guidelinesは、Amebaのサービスのアクセシビリティを高めるために設けた制作指針集である。「誰もがいつでも迷わずコンテンツを楽しむことができる」ようにするため、WCAG2.1を要約・和訳し、事例などを掲載している。
hasCJKLanguage: true
summaryLength: 130
disableKinds:
  - taxonomy
  - taxonomyTerm
